// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordmover.proto

package recordmover

import (
	fmt "fmt"
	proto1 "github.com/brotherlogic/recordcollection/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RecordedMove struct {
	// The record being moved
	InstanceId int32 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// The time of the move
	MoveTime int64 `protobuf:"varint,2,opt,name=move_time,json=moveTime,proto3" json:"move_time,omitempty"`
	// The eventual destination of the move
	MoveLocation string `protobuf:"bytes,3,opt,name=move_location,json=moveLocation,proto3" json:"move_location,omitempty"`
	// The initial location of the move
	MoveStart string `protobuf:"bytes,4,opt,name=move_start,json=moveStart,proto3" json:"move_start,omitempty"`
	// The rule applied to make the move
	Rule                 string   `protobuf:"bytes,5,opt,name=rule,proto3" json:"rule,omitempty"`
	From                 int32    `protobuf:"varint,6,opt,name=from,proto3" json:"from,omitempty"`
	To                   int32    `protobuf:"varint,7,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordedMove) Reset()         { *m = RecordedMove{} }
func (m *RecordedMove) String() string { return proto.CompactTextString(m) }
func (*RecordedMove) ProtoMessage()    {}
func (*RecordedMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{0}
}

func (m *RecordedMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordedMove.Unmarshal(m, b)
}
func (m *RecordedMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordedMove.Marshal(b, m, deterministic)
}
func (m *RecordedMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordedMove.Merge(m, src)
}
func (m *RecordedMove) XXX_Size() int {
	return xxx_messageInfo_RecordedMove.Size(m)
}
func (m *RecordedMove) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordedMove.DiscardUnknown(m)
}

var xxx_messageInfo_RecordedMove proto.InternalMessageInfo

func (m *RecordedMove) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *RecordedMove) GetMoveTime() int64 {
	if m != nil {
		return m.MoveTime
	}
	return 0
}

func (m *RecordedMove) GetMoveLocation() string {
	if m != nil {
		return m.MoveLocation
	}
	return ""
}

func (m *RecordedMove) GetMoveStart() string {
	if m != nil {
		return m.MoveStart
	}
	return ""
}

func (m *RecordedMove) GetRule() string {
	if m != nil {
		return m.Rule
	}
	return ""
}

func (m *RecordedMove) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *RecordedMove) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

type Config struct {
	Moves                []*RecordMove   `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	MoveArchive          []*RecordedMove `protobuf:"bytes,2,rep,name=move_archive,json=moveArchive,proto3" json:"move_archive,omitempty"`
	LastPull             int64           `protobuf:"varint,3,opt,name=last_pull,json=lastPull,proto3" json:"last_pull,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetMoves() []*RecordMove {
	if m != nil {
		return m.Moves
	}
	return nil
}

func (m *Config) GetMoveArchive() []*RecordedMove {
	if m != nil {
		return m.MoveArchive
	}
	return nil
}

func (m *Config) GetLastPull() int64 {
	if m != nil {
		return m.LastPull
	}
	return 0
}

type Context struct {
	Before               *proto1.Record `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	BeforeInstance       int32          `protobuf:"varint,5,opt,name=before_instance,json=beforeInstance,proto3" json:"before_instance,omitempty"`
	Location             string         `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	After                *proto1.Record `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	AfterInstance        int32          `protobuf:"varint,6,opt,name=after_instance,json=afterInstance,proto3" json:"after_instance,omitempty"`
	Slot                 int32          `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{2}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetBefore() *proto1.Record {
	if m != nil {
		return m.Before
	}
	return nil
}

func (m *Context) GetBeforeInstance() int32 {
	if m != nil {
		return m.BeforeInstance
	}
	return 0
}

func (m *Context) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Context) GetAfter() *proto1.Record {
	if m != nil {
		return m.After
	}
	return nil
}

func (m *Context) GetAfterInstance() int32 {
	if m != nil {
		return m.AfterInstance
	}
	return 0
}

func (m *Context) GetSlot() int32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

type RecordMove struct {
	InstanceId           int32          `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FromFolder           int32          `protobuf:"varint,2,opt,name=from_folder,json=fromFolder,proto3" json:"from_folder,omitempty"`
	ToFolder             int32          `protobuf:"varint,3,opt,name=to_folder,json=toFolder,proto3" json:"to_folder,omitempty"`
	MoveDate             int64          `protobuf:"varint,4,opt,name=move_date,json=moveDate,proto3" json:"move_date,omitempty"`
	Record               *proto1.Record `protobuf:"bytes,5,opt,name=record,proto3" json:"record,omitempty"`
	BeforeContext        *Context       `protobuf:"bytes,6,opt,name=before_context,json=beforeContext,proto3" json:"before_context,omitempty"`
	AfterContext         *Context       `protobuf:"bytes,7,opt,name=after_context,json=afterContext,proto3" json:"after_context,omitempty"`
	LastUpdate           int64          `protobuf:"varint,8,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RecordMove) Reset()         { *m = RecordMove{} }
func (m *RecordMove) String() string { return proto.CompactTextString(m) }
func (*RecordMove) ProtoMessage()    {}
func (*RecordMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{3}
}

func (m *RecordMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordMove.Unmarshal(m, b)
}
func (m *RecordMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordMove.Marshal(b, m, deterministic)
}
func (m *RecordMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordMove.Merge(m, src)
}
func (m *RecordMove) XXX_Size() int {
	return xxx_messageInfo_RecordMove.Size(m)
}
func (m *RecordMove) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordMove.DiscardUnknown(m)
}

var xxx_messageInfo_RecordMove proto.InternalMessageInfo

func (m *RecordMove) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *RecordMove) GetFromFolder() int32 {
	if m != nil {
		return m.FromFolder
	}
	return 0
}

func (m *RecordMove) GetToFolder() int32 {
	if m != nil {
		return m.ToFolder
	}
	return 0
}

func (m *RecordMove) GetMoveDate() int64 {
	if m != nil {
		return m.MoveDate
	}
	return 0
}

func (m *RecordMove) GetRecord() *proto1.Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *RecordMove) GetBeforeContext() *Context {
	if m != nil {
		return m.BeforeContext
	}
	return nil
}

func (m *RecordMove) GetAfterContext() *Context {
	if m != nil {
		return m.AfterContext
	}
	return nil
}

func (m *RecordMove) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

type Moves struct {
	Moves                []*RecordMove `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Moves) Reset()         { *m = Moves{} }
func (m *Moves) String() string { return proto.CompactTextString(m) }
func (*Moves) ProtoMessage()    {}
func (*Moves) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{4}
}

func (m *Moves) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Moves.Unmarshal(m, b)
}
func (m *Moves) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Moves.Marshal(b, m, deterministic)
}
func (m *Moves) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Moves.Merge(m, src)
}
func (m *Moves) XXX_Size() int {
	return xxx_messageInfo_Moves.Size(m)
}
func (m *Moves) XXX_DiscardUnknown() {
	xxx_messageInfo_Moves.DiscardUnknown(m)
}

var xxx_messageInfo_Moves proto.InternalMessageInfo

func (m *Moves) GetMoves() []*RecordMove {
	if m != nil {
		return m.Moves
	}
	return nil
}

type MoveRequest struct {
	Move                 *RecordMove `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{5}
}

func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (m *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(m, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetMove() *RecordMove {
	if m != nil {
		return m.Move
	}
	return nil
}

type MoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{6}
}

func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (m *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(m, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{7}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Moves                []*RecordMove   `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	Archives             []*RecordedMove `protobuf:"bytes,2,rep,name=archives,proto3" json:"archives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{8}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetMoves() []*RecordMove {
	if m != nil {
		return m.Moves
	}
	return nil
}

func (m *ListResponse) GetArchives() []*RecordedMove {
	if m != nil {
		return m.Archives
	}
	return nil
}

type ClearRequest struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearRequest) Reset()         { *m = ClearRequest{} }
func (m *ClearRequest) String() string { return proto.CompactTextString(m) }
func (*ClearRequest) ProtoMessage()    {}
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{9}
}

func (m *ClearRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearRequest.Unmarshal(m, b)
}
func (m *ClearRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearRequest.Marshal(b, m, deterministic)
}
func (m *ClearRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearRequest.Merge(m, src)
}
func (m *ClearRequest) XXX_Size() int {
	return xxx_messageInfo_ClearRequest.Size(m)
}
func (m *ClearRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearRequest proto.InternalMessageInfo

func (m *ClearRequest) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type ClearResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearResponse) Reset()         { *m = ClearResponse{} }
func (m *ClearResponse) String() string { return proto.CompactTextString(m) }
func (*ClearResponse) ProtoMessage()    {}
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{10}
}

func (m *ClearResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearResponse.Unmarshal(m, b)
}
func (m *ClearResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearResponse.Marshal(b, m, deterministic)
}
func (m *ClearResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearResponse.Merge(m, src)
}
func (m *ClearResponse) XXX_Size() int {
	return xxx_messageInfo_ClearResponse.Size(m)
}
func (m *ClearResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearResponse proto.InternalMessageInfo

type ForceRequest struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForceRequest) Reset()         { *m = ForceRequest{} }
func (m *ForceRequest) String() string { return proto.CompactTextString(m) }
func (*ForceRequest) ProtoMessage()    {}
func (*ForceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{11}
}

func (m *ForceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForceRequest.Unmarshal(m, b)
}
func (m *ForceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForceRequest.Marshal(b, m, deterministic)
}
func (m *ForceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForceRequest.Merge(m, src)
}
func (m *ForceRequest) XXX_Size() int {
	return xxx_messageInfo_ForceRequest.Size(m)
}
func (m *ForceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForceRequest proto.InternalMessageInfo

func (m *ForceRequest) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type ForceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForceResponse) Reset()         { *m = ForceResponse{} }
func (m *ForceResponse) String() string { return proto.CompactTextString(m) }
func (*ForceResponse) ProtoMessage()    {}
func (*ForceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{12}
}

func (m *ForceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForceResponse.Unmarshal(m, b)
}
func (m *ForceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForceResponse.Marshal(b, m, deterministic)
}
func (m *ForceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForceResponse.Merge(m, src)
}
func (m *ForceResponse) XXX_Size() int {
	return xxx_messageInfo_ForceResponse.Size(m)
}
func (m *ForceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RecordedMove)(nil), "recordmover.RecordedMove")
	proto.RegisterType((*Config)(nil), "recordmover.Config")
	proto.RegisterType((*Context)(nil), "recordmover.Context")
	proto.RegisterType((*RecordMove)(nil), "recordmover.RecordMove")
	proto.RegisterType((*Moves)(nil), "recordmover.Moves")
	proto.RegisterType((*MoveRequest)(nil), "recordmover.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "recordmover.MoveResponse")
	proto.RegisterType((*ListRequest)(nil), "recordmover.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "recordmover.ListResponse")
	proto.RegisterType((*ClearRequest)(nil), "recordmover.ClearRequest")
	proto.RegisterType((*ClearResponse)(nil), "recordmover.ClearResponse")
	proto.RegisterType((*ForceRequest)(nil), "recordmover.ForceRequest")
	proto.RegisterType((*ForceResponse)(nil), "recordmover.ForceResponse")
}

func init() { proto.RegisterFile("recordmover.proto", fileDescriptor_8a16ecfaf2b6a48f) }

var fileDescriptor_8a16ecfaf2b6a48f = []byte{
	// 695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6a, 0xdb, 0x4c,
	0x10, 0x8d, 0x6c, 0xcb, 0xb1, 0x47, 0xb2, 0xc3, 0xb7, 0x7c, 0x50, 0xc5, 0xa5, 0xc4, 0x6c, 0x29,
	0x35, 0x94, 0xda, 0xc5, 0xa5, 0x85, 0xfe, 0xdc, 0xb4, 0x4e, 0x03, 0x81, 0x04, 0xca, 0xa6, 0xbd,
	0x16, 0xb2, 0xbc, 0x4e, 0x04, 0x6b, 0xaf, 0xbb, 0x5a, 0x9b, 0x3e, 0x47, 0x1f, 0xa1, 0x4f, 0xd3,
	0xfb, 0x3e, 0x46, 0x5f, 0xa2, 0xec, 0xec, 0xda, 0x91, 0x12, 0x37, 0xc1, 0x77, 0xab, 0x33, 0x67,
	0x66, 0xe7, 0x9c, 0x99, 0x45, 0xf0, 0x9f, 0xe2, 0xa9, 0x54, 0x93, 0x99, 0x5c, 0x71, 0xd5, 0x5f,
	0x28, 0xa9, 0x25, 0x09, 0x0a, 0x50, 0xe7, 0xd3, 0x65, 0xa6, 0xaf, 0x96, 0xe3, 0x7e, 0x2a, 0x67,
	0x83, 0xb1, 0x92, 0xfa, 0x8a, 0x2b, 0x21, 0x2f, 0xb3, 0x74, 0x60, 0x49, 0xa9, 0x14, 0x82, 0xa7,
	0x3a, 0x93, 0xf3, 0x01, 0x26, 0xdf, 0x82, 0x6d, 0x4d, 0xfa, 0xcb, 0x83, 0x90, 0x61, 0x88, 0x4f,
	0xce, 0xe5, 0x8a, 0x93, 0x23, 0x08, 0xb2, 0x79, 0xae, 0x93, 0x79, 0xca, 0xe3, 0x6c, 0x12, 0x79,
	0x5d, 0xaf, 0xe7, 0x33, 0x58, 0x43, 0xa7, 0x13, 0xf2, 0x10, 0x9a, 0xa6, 0x83, 0x58, 0x67, 0x33,
	0x1e, 0x55, 0xba, 0x5e, 0xaf, 0xca, 0x1a, 0x06, 0xf8, 0x92, 0xcd, 0x38, 0x79, 0x0c, 0x2d, 0x0c,
	0x0a, 0x99, 0x26, 0xe6, 0x96, 0xa8, 0xda, 0xf5, 0x7a, 0x4d, 0x16, 0x1a, 0xf0, 0xcc, 0x61, 0xe4,
	0x11, 0x00, 0x92, 0x72, 0x9d, 0x28, 0x1d, 0xd5, 0x90, 0x81, 0x35, 0x2f, 0x0c, 0x40, 0x08, 0xd4,
	0xd4, 0x52, 0xf0, 0xc8, 0xc7, 0x00, 0x9e, 0x0d, 0x36, 0x55, 0x72, 0x16, 0xd5, 0xb1, 0x1d, 0x3c,
	0x93, 0x36, 0x54, 0xb4, 0x8c, 0xf6, 0x11, 0xa9, 0x68, 0x49, 0x7f, 0x78, 0x50, 0x1f, 0xc9, 0xf9,
	0x34, 0xbb, 0x24, 0xcf, 0xc1, 0x37, 0xf5, 0xf2, 0xc8, 0xeb, 0x56, 0x7b, 0xc1, 0xf0, 0x41, 0xbf,
	0x68, 0xa6, 0x95, 0x6b, 0xc4, 0x32, 0xcb, 0x22, 0xef, 0x01, 0x1b, 0x8c, 0x13, 0x95, 0x5e, 0x65,
	0x2b, 0xa3, 0xca, 0x64, 0x1d, 0x6e, 0xc9, 0xb2, 0x26, 0xb1, 0xc0, 0x60, 0x1f, 0x2c, 0xdb, 0x18,
	0x22, 0x92, 0x5c, 0xc7, 0x8b, 0xa5, 0x10, 0xa8, 0xb7, 0xca, 0x1a, 0x06, 0xf8, 0xbc, 0x14, 0x82,
	0xfe, 0xf1, 0x60, 0x7f, 0x24, 0xe7, 0x9a, 0x7f, 0xd7, 0xe4, 0x05, 0xd4, 0xc7, 0x7c, 0x2a, 0x15,
	0x47, 0x57, 0x83, 0x61, 0xd4, 0xbf, 0x35, 0x14, 0x7b, 0x0b, 0x73, 0x3c, 0xf2, 0x14, 0x0e, 0xec,
	0x29, 0x5e, 0x0f, 0x00, 0x5d, 0xf1, 0x59, 0xdb, 0xc2, 0xa7, 0x0e, 0x25, 0x1d, 0x68, 0x6c, 0x2c,
	0xaf, 0xa0, 0x6f, 0x9b, 0x6f, 0xd2, 0x07, 0x3f, 0x99, 0x6a, 0xae, 0xb0, 0xb7, 0xbb, 0x6e, 0xb5,
	0x34, 0xf2, 0x04, 0xda, 0x78, 0xb8, 0xbe, 0xd3, 0xba, 0xde, 0x42, 0x74, 0x73, 0x25, 0x81, 0x5a,
	0x2e, 0xa4, 0x9d, 0x9f, 0xcf, 0xf0, 0x4c, 0x7f, 0x57, 0x00, 0xae, 0xed, 0xbd, 0x7f, 0x97, 0x8e,
	0x20, 0x30, 0xa3, 0x8c, 0xa7, 0x52, 0x4c, 0xb8, 0xc2, 0xce, 0x7d, 0x06, 0x06, 0x3a, 0x41, 0xc4,
	0x78, 0xab, 0xe5, 0x3a, 0x5c, 0xc5, 0x70, 0x43, 0xcb, 0xeb, 0x20, 0x8e, 0x6d, 0x92, 0x68, 0x8e,
	0x6d, 0xb8, 0x4d, 0x3c, 0x4e, 0x34, 0x37, 0x66, 0x5b, 0x9d, 0xe8, 0xd8, 0x9d, 0x66, 0xdb, 0x00,
	0x79, 0x07, 0xce, 0xd5, 0x38, 0xb5, 0x03, 0x43, 0xdd, 0xc1, 0xf0, 0xff, 0xd2, 0x1e, 0xb8, 0x61,
	0xb2, 0x96, 0xe5, 0xae, 0x67, 0xfb, 0x06, 0xac, 0x3d, 0x9b, 0xdc, 0xfd, 0x3b, 0x72, 0x43, 0xa4,
	0xae, 0x53, 0x8f, 0x20, 0xc0, 0xfd, 0x59, 0x2e, 0x50, 0x48, 0x03, 0x85, 0x80, 0x81, 0xbe, 0x22,
	0x42, 0x5f, 0x83, 0x7f, 0x8e, 0x7b, 0xba, 0xdb, 0x5a, 0xd3, 0xb7, 0x10, 0xe0, 0x27, 0xff, 0xb6,
	0xe4, 0xb9, 0x26, 0xcf, 0xa0, 0x66, 0x70, 0xb7, 0x7c, 0xff, 0x4c, 0x46, 0x12, 0x6d, 0x43, 0x68,
	0x73, 0xf3, 0x85, 0x9c, 0xe7, 0x9c, 0xb6, 0x20, 0x38, 0xcb, 0x72, 0xed, 0x6a, 0x51, 0x0d, 0xa1,
	0xfd, 0xb4, 0xe1, 0x5d, 0x1f, 0xdc, 0x2b, 0x68, 0xb8, 0xb7, 0x96, 0xdf, 0xff, 0xd8, 0x36, 0x54,
	0x3a, 0x80, 0x70, 0x24, 0x78, 0xa2, 0xd6, 0x8a, 0xee, 0xdb, 0x2f, 0x7a, 0x00, 0x2d, 0x97, 0xe0,
	0x64, 0x0c, 0x20, 0x3c, 0x91, 0x2a, 0xe5, 0xbb, 0x54, 0x70, 0x09, 0xb6, 0xc2, 0xf0, 0x67, 0xc5,
	0xba, 0x7a, 0xc1, 0xd5, 0x2a, 0x4b, 0x39, 0x19, 0x95, 0x36, 0x3e, 0x2a, 0xc9, 0x28, 0xb8, 0xdf,
	0x39, 0xdc, 0x12, 0x71, 0x4d, 0xed, 0x91, 0x8f, 0xd0, 0x34, 0x76, 0xda, 0x29, 0x97, 0x6b, 0x14,
	0x5c, 0xbf, 0x51, 0xa3, 0x38, 0x00, 0xba, 0x47, 0x8e, 0xa1, 0x89, 0x5a, 0xb1, 0x8f, 0x32, 0xb3,
	0x68, 0x5a, 0xa7, 0xb3, 0x2d, 0x54, 0xac, 0x82, 0x7a, 0xb7, 0x54, 0x29, 0x1a, 0x77, 0xa3, 0x4a,
	0xc9, 0x22, 0xba, 0x37, 0xae, 0xe3, 0xcf, 0xe5, 0xe5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a,
	0xe7, 0xe6, 0x1a, 0xc5, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MoveServiceClient is the client API for MoveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MoveServiceClient interface {
	RecordMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
	ListMoves(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ClearMove(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
	ForceMove(ctx context.Context, in *ForceRequest, opts ...grpc.CallOption) (*ForceResponse, error)
}

type moveServiceClient struct {
	cc *grpc.ClientConn
}

func NewMoveServiceClient(cc *grpc.ClientConn) MoveServiceClient {
	return &moveServiceClient{cc}
}

func (c *moveServiceClient) RecordMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/recordmover.MoveService/RecordMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moveServiceClient) ListMoves(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/recordmover.MoveService/ListMoves", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moveServiceClient) ClearMove(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	out := new(ClearResponse)
	err := c.cc.Invoke(ctx, "/recordmover.MoveService/ClearMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moveServiceClient) ForceMove(ctx context.Context, in *ForceRequest, opts ...grpc.CallOption) (*ForceResponse, error) {
	out := new(ForceResponse)
	err := c.cc.Invoke(ctx, "/recordmover.MoveService/ForceMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoveServiceServer is the server API for MoveService service.
type MoveServiceServer interface {
	RecordMove(context.Context, *MoveRequest) (*MoveResponse, error)
	ListMoves(context.Context, *ListRequest) (*ListResponse, error)
	ClearMove(context.Context, *ClearRequest) (*ClearResponse, error)
	ForceMove(context.Context, *ForceRequest) (*ForceResponse, error)
}

func RegisterMoveServiceServer(s *grpc.Server, srv MoveServiceServer) {
	s.RegisterService(&_MoveService_serviceDesc, srv)
}

func _MoveService_RecordMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).RecordMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordmover.MoveService/RecordMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).RecordMove(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoveService_ListMoves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).ListMoves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordmover.MoveService/ListMoves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).ListMoves(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoveService_ClearMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).ClearMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordmover.MoveService/ClearMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).ClearMove(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoveService_ForceMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).ForceMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordmover.MoveService/ForceMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).ForceMove(ctx, req.(*ForceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MoveService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recordmover.MoveService",
	HandlerType: (*MoveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordMove",
			Handler:    _MoveService_RecordMove_Handler,
		},
		{
			MethodName: "ListMoves",
			Handler:    _MoveService_ListMoves_Handler,
		},
		{
			MethodName: "ClearMove",
			Handler:    _MoveService_ClearMove_Handler,
		},
		{
			MethodName: "ForceMove",
			Handler:    _MoveService_ForceMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordmover.proto",
}
