// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordmover.proto

package recordprocessor

import (
	fmt "fmt"
	proto1 "github.com/brotherlogic/recordcollection/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RecordMove struct {
	InstanceId           int32          `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FromFolder           int32          `protobuf:"varint,2,opt,name=from_folder,json=fromFolder,proto3" json:"from_folder,omitempty"`
	ToFolder             int32          `protobuf:"varint,3,opt,name=to_folder,json=toFolder,proto3" json:"to_folder,omitempty"`
	MoveDate             int64          `protobuf:"varint,4,opt,name=move_date,json=moveDate,proto3" json:"move_date,omitempty"`
	Record               *proto1.Record `protobuf:"bytes,5,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RecordMove) Reset()         { *m = RecordMove{} }
func (m *RecordMove) String() string { return proto.CompactTextString(m) }
func (*RecordMove) ProtoMessage()    {}
func (*RecordMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{0}
}

func (m *RecordMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordMove.Unmarshal(m, b)
}
func (m *RecordMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordMove.Marshal(b, m, deterministic)
}
func (m *RecordMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordMove.Merge(m, src)
}
func (m *RecordMove) XXX_Size() int {
	return xxx_messageInfo_RecordMove.Size(m)
}
func (m *RecordMove) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordMove.DiscardUnknown(m)
}

var xxx_messageInfo_RecordMove proto.InternalMessageInfo

func (m *RecordMove) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *RecordMove) GetFromFolder() int32 {
	if m != nil {
		return m.FromFolder
	}
	return 0
}

func (m *RecordMove) GetToFolder() int32 {
	if m != nil {
		return m.ToFolder
	}
	return 0
}

func (m *RecordMove) GetMoveDate() int64 {
	if m != nil {
		return m.MoveDate
	}
	return 0
}

func (m *RecordMove) GetRecord() *proto1.Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type Moves struct {
	Moves                []*RecordMove `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Moves) Reset()         { *m = Moves{} }
func (m *Moves) String() string { return proto.CompactTextString(m) }
func (*Moves) ProtoMessage()    {}
func (*Moves) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{1}
}

func (m *Moves) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Moves.Unmarshal(m, b)
}
func (m *Moves) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Moves.Marshal(b, m, deterministic)
}
func (m *Moves) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Moves.Merge(m, src)
}
func (m *Moves) XXX_Size() int {
	return xxx_messageInfo_Moves.Size(m)
}
func (m *Moves) XXX_DiscardUnknown() {
	xxx_messageInfo_Moves.DiscardUnknown(m)
}

var xxx_messageInfo_Moves proto.InternalMessageInfo

func (m *Moves) GetMoves() []*RecordMove {
	if m != nil {
		return m.Moves
	}
	return nil
}

type MoveRequest struct {
	Move                 *RecordMove `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{2}
}

func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (m *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(m, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetMove() *RecordMove {
	if m != nil {
		return m.Move
	}
	return nil
}

type MoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{3}
}

func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (m *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(m, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{4}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Moves                []*RecordMove `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{5}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetMoves() []*RecordMove {
	if m != nil {
		return m.Moves
	}
	return nil
}

type ClearRequest struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearRequest) Reset()         { *m = ClearRequest{} }
func (m *ClearRequest) String() string { return proto.CompactTextString(m) }
func (*ClearRequest) ProtoMessage()    {}
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{6}
}

func (m *ClearRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearRequest.Unmarshal(m, b)
}
func (m *ClearRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearRequest.Marshal(b, m, deterministic)
}
func (m *ClearRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearRequest.Merge(m, src)
}
func (m *ClearRequest) XXX_Size() int {
	return xxx_messageInfo_ClearRequest.Size(m)
}
func (m *ClearRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearRequest proto.InternalMessageInfo

func (m *ClearRequest) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type ClearResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearResponse) Reset()         { *m = ClearResponse{} }
func (m *ClearResponse) String() string { return proto.CompactTextString(m) }
func (*ClearResponse) ProtoMessage()    {}
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a16ecfaf2b6a48f, []int{7}
}

func (m *ClearResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearResponse.Unmarshal(m, b)
}
func (m *ClearResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearResponse.Marshal(b, m, deterministic)
}
func (m *ClearResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearResponse.Merge(m, src)
}
func (m *ClearResponse) XXX_Size() int {
	return xxx_messageInfo_ClearResponse.Size(m)
}
func (m *ClearResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RecordMove)(nil), "recordprocessor.RecordMove")
	proto.RegisterType((*Moves)(nil), "recordprocessor.Moves")
	proto.RegisterType((*MoveRequest)(nil), "recordprocessor.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "recordprocessor.MoveResponse")
	proto.RegisterType((*ListRequest)(nil), "recordprocessor.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "recordprocessor.ListResponse")
	proto.RegisterType((*ClearRequest)(nil), "recordprocessor.ClearRequest")
	proto.RegisterType((*ClearResponse)(nil), "recordprocessor.ClearResponse")
}

func init() { proto.RegisterFile("recordmover.proto", fileDescriptor_8a16ecfaf2b6a48f) }

var fileDescriptor_8a16ecfaf2b6a48f = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcf, 0xee, 0xd2, 0x40,
	0x18, 0xfc, 0x55, 0x28, 0x81, 0xaf, 0x20, 0x71, 0x4f, 0x0d, 0xf8, 0xa7, 0xd9, 0x53, 0x4f, 0xad,
	0xe2, 0xcd, 0x83, 0x89, 0xf1, 0x4f, 0xa2, 0xe2, 0xa5, 0x3e, 0x00, 0x29, 0xdb, 0x0f, 0x68, 0x52,
	0xfa, 0xe1, 0xee, 0xc2, 0xc3, 0xf9, 0x5c, 0x3e, 0x80, 0xd9, 0xdd, 0x36, 0x54, 0x2b, 0x21, 0xf1,
	0xb8, 0x33, 0xb3, 0xd3, 0x99, 0xd9, 0xc2, 0x13, 0x89, 0x82, 0x64, 0x71, 0xa4, 0x0b, 0xca, 0xe4,
	0x24, 0x49, 0x13, 0x9b, 0x3b, 0xe8, 0x24, 0x49, 0xa0, 0x52, 0x24, 0x17, 0x1f, 0xf7, 0xa5, 0x3e,
	0x9c, 0xb7, 0x89, 0xa0, 0x63, 0xba, 0x95, 0xa4, 0x0f, 0x28, 0x2b, 0xda, 0x97, 0x22, 0x75, 0x42,
	0x41, 0x55, 0x85, 0x42, 0x97, 0x54, 0xa7, 0xd6, 0xa0, 0x07, 0x3b, 0x5f, 0xfe, 0xd3, 0x03, 0xc8,
	0x2c, 0xf5, 0x8d, 0x2e, 0xc8, 0x5e, 0x40, 0x50, 0xd6, 0x4a, 0xe7, 0xb5, 0xc0, 0x4d, 0x59, 0x84,
	0x5e, 0xe4, 0xc5, 0x7e, 0x06, 0x2d, 0xf4, 0xb9, 0x30, 0x82, 0x9d, 0xa4, 0xe3, 0x66, 0x47, 0x55,
	0x81, 0x32, 0x7c, 0xe4, 0x04, 0x06, 0xfa, 0x64, 0x11, 0xb6, 0x84, 0x89, 0xa6, 0x96, 0x1e, 0x58,
	0x7a, 0xac, 0xe9, 0x4a, 0x9a, 0x52, 0x9b, 0x22, 0xd7, 0x18, 0x0e, 0x23, 0x2f, 0x1e, 0x64, 0x63,
	0x03, 0x7c, 0xc8, 0x35, 0xb2, 0x97, 0x30, 0x72, 0x21, 0x43, 0x3f, 0xf2, 0xe2, 0x60, 0x15, 0x26,
	0xbd, 0xcc, 0x2e, 0x69, 0xd6, 0xe8, 0xf8, 0x1b, 0xf0, 0x4d, 0x6a, 0xc5, 0x5e, 0x81, 0x6f, 0x6c,
	0x54, 0xe8, 0x45, 0x83, 0x38, 0x58, 0x2d, 0x93, 0xbf, 0xd6, 0x4a, 0xae, 0x15, 0x33, 0xa7, 0xe4,
	0x6f, 0x21, 0xb0, 0x47, 0xfc, 0x71, 0x46, 0xa5, 0x59, 0x0a, 0x43, 0x83, 0xdb, 0xc6, 0x77, 0x0c,
	0xac, 0x90, 0x3f, 0x86, 0xa9, 0xbb, 0xaf, 0x4e, 0x54, 0x2b, 0xe4, 0x33, 0x08, 0xd6, 0xa5, 0xd2,
	0x8d, 0x1f, 0x7f, 0x07, 0x53, 0x77, 0x74, 0xf4, 0xff, 0x24, 0x4c, 0x61, 0xfa, 0xbe, 0xc2, 0x5c,
	0xb6, 0x11, 0xef, 0xbd, 0x0d, 0x9f, 0xc3, 0xac, 0xb9, 0xe0, 0x3e, 0xba, 0xfa, 0xe5, 0xb9, 0x92,
	0xdf, 0x51, 0x5e, 0x4a, 0x81, 0xec, 0xeb, 0x1f, 0x6f, 0xfd, 0xb4, 0x97, 0xa1, 0x33, 0xc8, 0xe2,
	0xd9, 0x0d, 0xb6, 0xa9, 0xfb, 0xc0, 0xbe, 0xc0, 0xc4, 0x34, 0x74, 0x0f, 0xd0, 0xf7, 0xea, 0x8c,
	0xf1, 0x0f, 0xaf, 0xee, 0x36, 0xfc, 0x81, 0xad, 0x61, 0x62, 0x93, 0xdb, 0x5c, 0x7d, 0x75, 0x77,
	0x86, 0xc5, 0xf3, 0x5b, 0x74, 0xeb, 0xb6, 0x1d, 0xd9, 0x5f, 0xfb, 0xf5, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x49, 0x75, 0x1b, 0x78, 0x47, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MoveServiceClient is the client API for MoveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MoveServiceClient interface {
	RecordMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
	ListMoves(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ClearMove(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
}

type moveServiceClient struct {
	cc *grpc.ClientConn
}

func NewMoveServiceClient(cc *grpc.ClientConn) MoveServiceClient {
	return &moveServiceClient{cc}
}

func (c *moveServiceClient) RecordMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/recordprocessor.MoveService/RecordMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moveServiceClient) ListMoves(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/recordprocessor.MoveService/ListMoves", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moveServiceClient) ClearMove(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	out := new(ClearResponse)
	err := c.cc.Invoke(ctx, "/recordprocessor.MoveService/ClearMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoveServiceServer is the server API for MoveService service.
type MoveServiceServer interface {
	RecordMove(context.Context, *MoveRequest) (*MoveResponse, error)
	ListMoves(context.Context, *ListRequest) (*ListResponse, error)
	ClearMove(context.Context, *ClearRequest) (*ClearResponse, error)
}

func RegisterMoveServiceServer(s *grpc.Server, srv MoveServiceServer) {
	s.RegisterService(&_MoveService_serviceDesc, srv)
}

func _MoveService_RecordMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).RecordMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordprocessor.MoveService/RecordMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).RecordMove(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoveService_ListMoves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).ListMoves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordprocessor.MoveService/ListMoves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).ListMoves(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoveService_ClearMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).ClearMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordprocessor.MoveService/ClearMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).ClearMove(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MoveService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recordprocessor.MoveService",
	HandlerType: (*MoveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordMove",
			Handler:    _MoveService_RecordMove_Handler,
		},
		{
			MethodName: "ListMoves",
			Handler:    _MoveService_ListMoves_Handler,
		},
		{
			MethodName: "ClearMove",
			Handler:    _MoveService_ClearMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordmover.proto",
}
