// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordmover.proto

/*
Package recordprocessor is a generated protocol buffer package.

It is generated from these files:
	recordmover.proto

It has these top-level messages:
	RecordMove
	Moves
	MoveRequest
	MoveResponse
	ListRequest
	ListResponse
	ClearRequest
	ClearResponse
*/
package recordprocessor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RecordMove struct {
	InstanceId int32 `protobuf:"varint,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	FromFolder int32 `protobuf:"varint,2,opt,name=from_folder,json=fromFolder" json:"from_folder,omitempty"`
	ToFolder   int32 `protobuf:"varint,3,opt,name=to_folder,json=toFolder" json:"to_folder,omitempty"`
	MoveDate   int64 `protobuf:"varint,4,opt,name=move_date,json=moveDate" json:"move_date,omitempty"`
}

func (m *RecordMove) Reset()                    { *m = RecordMove{} }
func (m *RecordMove) String() string            { return proto.CompactTextString(m) }
func (*RecordMove) ProtoMessage()               {}
func (*RecordMove) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RecordMove) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *RecordMove) GetFromFolder() int32 {
	if m != nil {
		return m.FromFolder
	}
	return 0
}

func (m *RecordMove) GetToFolder() int32 {
	if m != nil {
		return m.ToFolder
	}
	return 0
}

func (m *RecordMove) GetMoveDate() int64 {
	if m != nil {
		return m.MoveDate
	}
	return 0
}

type Moves struct {
	Moves []*RecordMove `protobuf:"bytes,1,rep,name=moves" json:"moves,omitempty"`
}

func (m *Moves) Reset()                    { *m = Moves{} }
func (m *Moves) String() string            { return proto.CompactTextString(m) }
func (*Moves) ProtoMessage()               {}
func (*Moves) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Moves) GetMoves() []*RecordMove {
	if m != nil {
		return m.Moves
	}
	return nil
}

type MoveRequest struct {
	Move *RecordMove `protobuf:"bytes,1,opt,name=move" json:"move,omitempty"`
}

func (m *MoveRequest) Reset()                    { *m = MoveRequest{} }
func (m *MoveRequest) String() string            { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()               {}
func (*MoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MoveRequest) GetMove() *RecordMove {
	if m != nil {
		return m.Move
	}
	return nil
}

type MoveResponse struct {
}

func (m *MoveResponse) Reset()                    { *m = MoveResponse{} }
func (m *MoveResponse) String() string            { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()               {}
func (*MoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ListResponse struct {
	Moves []*RecordMove `protobuf:"bytes,1,rep,name=moves" json:"moves,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListResponse) GetMoves() []*RecordMove {
	if m != nil {
		return m.Moves
	}
	return nil
}

type ClearRequest struct {
	InstanceId int32 `protobuf:"varint,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *ClearRequest) Reset()                    { *m = ClearRequest{} }
func (m *ClearRequest) String() string            { return proto.CompactTextString(m) }
func (*ClearRequest) ProtoMessage()               {}
func (*ClearRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ClearRequest) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type ClearResponse struct {
}

func (m *ClearResponse) Reset()                    { *m = ClearResponse{} }
func (m *ClearResponse) String() string            { return proto.CompactTextString(m) }
func (*ClearResponse) ProtoMessage()               {}
func (*ClearResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*RecordMove)(nil), "recordprocessor.RecordMove")
	proto.RegisterType((*Moves)(nil), "recordprocessor.Moves")
	proto.RegisterType((*MoveRequest)(nil), "recordprocessor.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "recordprocessor.MoveResponse")
	proto.RegisterType((*ListRequest)(nil), "recordprocessor.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "recordprocessor.ListResponse")
	proto.RegisterType((*ClearRequest)(nil), "recordprocessor.ClearRequest")
	proto.RegisterType((*ClearResponse)(nil), "recordprocessor.ClearResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MoveService service

type MoveServiceClient interface {
	RecordMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
	ListMoves(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ClearMove(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
}

type moveServiceClient struct {
	cc *grpc.ClientConn
}

func NewMoveServiceClient(cc *grpc.ClientConn) MoveServiceClient {
	return &moveServiceClient{cc}
}

func (c *moveServiceClient) RecordMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := grpc.Invoke(ctx, "/recordprocessor.MoveService/RecordMove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moveServiceClient) ListMoves(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/recordprocessor.MoveService/ListMoves", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moveServiceClient) ClearMove(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	out := new(ClearResponse)
	err := grpc.Invoke(ctx, "/recordprocessor.MoveService/ClearMove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MoveService service

type MoveServiceServer interface {
	RecordMove(context.Context, *MoveRequest) (*MoveResponse, error)
	ListMoves(context.Context, *ListRequest) (*ListResponse, error)
	ClearMove(context.Context, *ClearRequest) (*ClearResponse, error)
}

func RegisterMoveServiceServer(s *grpc.Server, srv MoveServiceServer) {
	s.RegisterService(&_MoveService_serviceDesc, srv)
}

func _MoveService_RecordMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).RecordMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordprocessor.MoveService/RecordMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).RecordMove(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoveService_ListMoves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).ListMoves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordprocessor.MoveService/ListMoves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).ListMoves(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoveService_ClearMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).ClearMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordprocessor.MoveService/ClearMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).ClearMove(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MoveService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recordprocessor.MoveService",
	HandlerType: (*MoveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordMove",
			Handler:    _MoveService_RecordMove_Handler,
		},
		{
			MethodName: "ListMoves",
			Handler:    _MoveService_ListMoves_Handler,
		},
		{
			MethodName: "ClearMove",
			Handler:    _MoveService_ClearMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordmover.proto",
}

func init() { proto.RegisterFile("recordmover.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0x99, 0x0f, 0xf8, 0x02, 0xb7, 0x20, 0x71, 0x56, 0x0d, 0xf8, 0x87, 0xcc, 0x8a, 0x15,
	0x44, 0xdc, 0xb9, 0x30, 0x31, 0x1a, 0x13, 0x15, 0x37, 0xf5, 0x01, 0x9a, 0xda, 0x5e, 0x92, 0x26,
	0xd0, 0x5b, 0x67, 0xc6, 0x3e, 0x83, 0x0f, 0xec, 0x03, 0x98, 0x99, 0x69, 0x43, 0xb5, 0x12, 0x12,
	0x97, 0x73, 0xce, 0x9d, 0xd3, 0xdf, 0x3d, 0x53, 0x38, 0x96, 0x18, 0x93, 0x4c, 0xb6, 0x54, 0xa0,
	0x9c, 0xe7, 0x92, 0x34, 0xf1, 0x91, 0x93, 0x72, 0x49, 0x31, 0x2a, 0x45, 0x52, 0x7c, 0x30, 0x80,
	0xc0, 0x6a, 0xcf, 0x54, 0x20, 0x3f, 0x07, 0x2f, 0xcd, 0x94, 0x8e, 0xb2, 0x18, 0xc3, 0x34, 0xf1,
	0xd9, 0x94, 0xcd, 0xba, 0x01, 0x54, 0xd2, 0x43, 0x62, 0x06, 0xd6, 0x92, 0xb6, 0xe1, 0x9a, 0x36,
	0x09, 0x4a, 0xff, 0x9f, 0x1b, 0x30, 0xd2, 0xbd, 0x55, 0xf8, 0x04, 0xfa, 0x9a, 0x2a, 0xbb, 0x6d,
	0xed, 0x9e, 0xa6, 0x9d, 0x69, 0x68, 0xc2, 0x24, 0xd2, 0xe8, 0x77, 0xa6, 0x6c, 0xd6, 0x0e, 0x7a,
	0x46, 0xb8, 0x8b, 0x34, 0x8a, 0x2b, 0xe8, 0x1a, 0x06, 0xc5, 0x2f, 0xa0, 0x6b, 0x44, 0xe5, 0xb3,
	0x69, 0x7b, 0xe6, 0x2d, 0x27, 0xf3, 0x1f, 0xd0, 0xf3, 0x1d, 0x70, 0xe0, 0x26, 0xc5, 0x35, 0x78,
	0xf6, 0x88, 0x6f, 0xef, 0xa8, 0x34, 0x5f, 0x40, 0xc7, 0xe8, 0x96, 0xff, 0x40, 0x80, 0x1d, 0x14,
	0x47, 0x30, 0x70, 0xf7, 0x55, 0x4e, 0x99, 0x42, 0x31, 0x04, 0x6f, 0x95, 0x2a, 0x5d, 0xe6, 0x89,
	0x1b, 0x18, 0xb8, 0xa3, 0xb3, 0xff, 0x42, 0xb8, 0x80, 0xc1, 0xed, 0x06, 0x23, 0x59, 0x21, 0x1e,
	0x6a, 0x5a, 0x8c, 0x60, 0x58, 0x5e, 0x70, 0x1f, 0x5d, 0x7e, 0x32, 0xb7, 0xe4, 0x0b, 0xca, 0x22,
	0x8d, 0x91, 0x3f, 0x7d, 0x7b, 0xb9, 0x93, 0x06, 0x43, 0xad, 0x90, 0xf1, 0xe9, 0x1e, 0xb7, 0x5c,
	0xb7, 0xc5, 0x1f, 0xa1, 0x6f, 0x36, 0x74, 0x0f, 0xd0, 0xcc, 0xaa, 0x95, 0xf1, 0x4b, 0x56, 0xbd,
	0x1b, 0xd1, 0xe2, 0x2b, 0xe8, 0x5b, 0x72, 0xcb, 0xd5, 0x9c, 0xae, 0xd7, 0x30, 0x3e, 0xdb, 0x67,
	0x57, 0x69, 0xaf, 0xff, 0xed, 0x9f, 0x7b, 0xf9, 0x15, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x63, 0xf8,
	0x13, 0xce, 0x02, 0x00, 0x00,
}
